version: '3.4'
    
volumes:
    static:
    
services:

    webapp:
        restart: always
        build: webapp
        image: django_uwsgi
        links:
            - postgres:postgres
        volumes:
            - static:/var/www/djangopj/static
        command: /bin/ash -c "/home/docker/code/wait-for-it.sh postgres:5432 -t 60 && python3 /var/www/djangopj/manage.py migrate && supervisord -n -c /home/docker/code/supervisor-app.conf"
        expose:
            - "8000"
        depends_on:
            - postgres

    postgres:
        restart: always
        image: postgres:latest
        volumes:
            - ./_data/docker/psql:/var/lib/postgresql
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./backups/postgresql:/backup
        env_file:
            - ./webapp/.env
        expose:
            - "5432"

    nginx:
        restart: always
        image: nginx:alpine
        links:
            - webapp:webapp
        ports:
            - "80:80"
        volumes:
            - static:/var/www/djangopj/static
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./_log/nginx:/var/log/nginx